name = "${CLOUDFLARE_WORKER_NAME}"
type = "webpack"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
workers_dev = true
route = "${DOMAIN}/*"
zone_id = "${CLOUDFLARE_ZONE_ID}"
webpack_config = "webpack.config.js"

kv_namespaces = [
  { binding = "STORAGE", id = "${KV_STORAGE_ID}" }
]
vars = { ETH_RPC = "${ETH_RPC}", LINA_ADDRESS = "${LINA_ADDRESS}" }
